server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  packagesToScan: pl.piomin.services.department

spring:
  zipkin:
    discovery-client-enabled: true
    base-url: http://localhost:9061/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1